package com.github.gustavovitor.integracoes_api.api.service.auth_user.exceptions;

public class AuthUserAlreadyConfirmedException extends RuntimeException {
}
